### ISSUE TITLE
Add way to specify notation to be used for floats

### ISSUE THREAD

**Issue by leftshift** [artonge/go-csv-tag#10]
When `Dump`ing structs containing floats, the default representation is used. For high exponents, this is scientific notation, e.g. `1e-06` for `0.000001`.

This is incompatible with some specifications that use csv. Currently, there's no way of specifying which representation `go-csv-tag` should use. Similar situations may arrise for other types, like if an integer should be duped as a hexadeximal value.

**Comment by artonge** [comment]
I think the decimal format (e.g. 0.000001) to be more expected when dumping float, so I made it default in commit 91857aaca1bd8b595347eaa5604b93e393396a86.
