### ISSUE TITLE
Have you tested the LoadFromPath?

### ISSUE THREAD

**Issue by machelcheng** [artonge/go-csv-tag#20]
First use the example DumpToFile to generate a csv test file,  then use LoadFromPath to load this file, panic happened

generated csv file :
name, ID, number
'name1', 1, 1.2

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/artonge/go-csv-tag.mapToDestination(0xc0000c7f48, 0x3, 0x3, 0xc0000b4
330, 0x2, 0x2, 0x4bbf00, 0xc000096560, 0x3, 0xc0000b4330)
        E:/Go/gopath/src/github.com/artonge/go-csv-tag/load.go:182 +0xe9f
github.com/artonge/go-csv-tag.LoadFromReader(0x503ac0, 0xc0000ca028, 0x4bbf00, 0
xc000096560, 0xc0000c7f28, 0x1, 0x1, 0xc00008c8f0, 0xc0000a00c0)
        E:/Go/gopath/src/github.com/artonge/go-csv-tag/load.go:48 +0x17e
github.com/artonge/go-csv-tag.LoadFromPath(0x4e52c4, 0x11, 0x4bbf00, 0xc00009656
0, 0xc0000c7f28, 0x1, 0x1, 0x0, 0x0)
        E:/Go/gopath/src/github.com/artonge/go-csv-tag/load.go:78 +0x10b

**Comment by artonge** [comment]
Hi, thanks for reporting !
I'll take a look on Wednesday. Until then, feel free to open a fix if you got one ;).

**Comment by machelcheng** [comment]
> Hi, thanks for reporting !
> I'll take a look on Wednesday. Until then, feel free to open a fix if you got one ;).


Hello，I found the problem:
After readFile, the content is  [[name,ID,number] ['name1', 1, 1.2]]，and content type is [][]string.
You can see，content[0] and content[1] actually only one element， "name,ID,number"  and "'name1', 1, 1.2".
So if you access content[0][1]，panic will happened.

**Comment by artonge** [comment]
Hello,

I have been trying to reproduce with this test case, but with no success:

```go
func TestExample(t *testing.T) {
	type Demo struct {
		Name string  `csv:"name"`
		ID   int     `csv:"ID"`
		Num  float64 `csv:"number"`
	}

	err := DumpToFile([]Demo{
		Demo{
			Name: "some name",
			ID:   1,
			Num:  42.5,
		},
	}, "csv_file_name.csv")

	if err != nil {
		fmt.Println(err)
		t.Fail()
	}

	tab := []Demo{}
	err = LoadFromPath("csv_file_name.csv", &tab)

	if err != nil {
		fmt.Println(err)
		t.Fail()
	}

	fmt.Println(tab)
}
```

**Comment by artonge** [comment]
Hey @machelcheng, are you still having the problem ?
